# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16259c504cc62a1b7040558f377d5577e74eded21f4198105819b0fd7d69dc84b796785258b491b4f96afff37488c274adcfb21bf5ca8032bf823ccd680b2b54

test:
  secret_key_base: e78a580711b56d3115953499f1754660fea30c9cd2bbc9872c5eebe1e560cab1eb515c61eb9e03157435e497cafa33df1b1914ee1c0d4cb8cdd5c230d46bf077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
